apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eniiff4qr-nodejs 
  janus-idp.io/tekton: eniiff4qr-nodejs
  backstage.io/kubernetes-id: eniiff4qr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eniiff4qr-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  